package training.tangara.chrono.before;
import java.awt.*;
import javax.swing.JPanel;

	public class Cellule extends javax.swing.JPanel {
		 
		 
	    public Cellule() {
	        initComponents();
	    }
	 
	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    
	    
	    private void initComponents() {
	 
	        setBackground(new java.awt.Color(255, 255, 255));
	        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	 
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 66, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 63, Short.MAX_VALUE)
	        );
	    }// </editor-fold>
	 
	 
	    // Variables declaration - do not modify
	    // End of variables declaration
	 
	}


